<?php


	define("ROOT", "/home/paolo/code/dbthunder");
	define("CLIENT_DIR", ROOT."/client/rpcclient");
	define("SHARED_DIR", ROOT."/shared");

	define("RPCPROXY_GATEWAY",  "/rpc/crud.php");
	define("RPCPROXY_HOST",  "lulli.net");
	//define("RPCPROXY_HOST",  "lulli.net");
	define("RPCPROXY_PORT",  "80");
	define("RPCPROXY_USER",  "");
	define("RPCPROXY_PASS",  "");

	//define("BACKEND_DIR", "/home/blacksheep/apps/dbt");

	define("LOGROOT", CLIENT_DIR."/logs");

?>
