<?php

$res_name="ZZZ";
$res[$res_name]['type']="include.block";
$res[$res_name]['description']="__Edit this description__";
$res[$res_name]['externaltable']="RES_ZZZ";
$res[$res_name]['data']="data.inc";
$res[$res_name]['internal']="0";

/*
$res_name="zero";
$res[$res_name]['type']="include.block";
$res[$res_name]['description']="__Edit this description__";
$res[$res_name]['externaltable']="";
$res[$res_name]['data']="data.inc";
$res[$res_name]['internal']="1";
*/




?>
