
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
   <LINK rel="stylesheet" href="./css/default.css" type="text/css"/> 
   <LINK rel="shortcut icon" href="/favicon.ico" />
   <LINK rel="stylesheet" href="./css/droplist.css" type="text/css"/> 
   <script type="text/javascript" src="./js/web2.js"></script>

   <script type="text/javascript" src="./js/droplist.js"></script>
   <script type="text/javascript" src="./ext/fckeditor/fckeditor.js"></script>
<?php
//      require_once("settings.inc");
     
           echo "<script type=\"text/javascript\" src=\"".EXTJS_JSROOT."/ext-base.js\"></script>";
	   echo "<script type=\"text/javascript\" src=\"". EXTJSROOT."/ext-all-debug.js\"></script>";
	   echo "<script type=\"text/javascript\" src=\"Ajaxcall.js\"></script>";
	   echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"".EXTJS_CSSROOT."/ext-all.css\">";
	   echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"".EXTJS_CUSTOMROOT."/ExtStart.css\">";
?>




  <title>Hackbook</ title>

</head>
<body>


<div id="header"> 
<span class="logo"> hackbook </span>
<a href="/hbindex.php">Home</a>
<a href="/be/insert_user.php">AddUser</a>
<a href="/fe/fcktest.php">Edit</a>
<a href="/chat">Chat</a>
<a href="/blog">Blog</a>

<a href="http://shop.hackbook.org">Shop</a>
<a href="/blog">About</a>

</div>

<div id="left_column"> 



</div>
<div id="right_column">
</div>
<div id="corpus">
<!-- <div id="corpus"> -->

