<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_User">ID_User</input>
<input type="text" name="active">active</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="ID_Usergroup">ID_Usergroup</input>

<input type="submit" value="insert"></input>
</form>
