<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="ID_Resource">ID_Resource</input>
<input type="text" name="updated">updated</input>
<input type="text" name="ID_Role">ID_Role</input>
<input type="text" name="description">description</input>
<input type="text" name="perms">perms</input>

<input type="submit" value="insert"></input>
</form>
