<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
<form method="post" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>">
<input type="text" name="created">created</input>
<input type="text" name="name">name</input>
<input type="text" name="updated">updated</input>
<input type="text" name="description">description</input>

<input type="submit" value="insert"></input>
</form>
